services:
  - type: web
    name: mi-api-dotnet
    runtime: docker
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_URLS
        value: "http://0.0.0.0:${PORT}"
    dockerfilePath: ./Dockerfile
    plan: free
